apiVersion: batch/v1
kind: Job
metadata:
  name: beam-job-service
spec:
  ttlSecondsAfterFinished: 60
  template:
    spec:
      containers:
        - name: job-service
          image: job-service
          imagePullPolicy: Never
          volumeMounts:
            - mountPath: /tmp/beam-artifact-staging
              name: artifact-staging           
            - mountPath: /config
              name: config          
          env:
            - name: FLINK_CLUSTER
              value: "flink-session-rest:8081"
            - name: SAVEPOINTS_DIR
              value: "/flink-data/savepoints"
            - name: JAR_PATH
              value: "/jars/beam-runners-flink-1.16-job-server-2.49.0.jar"
      volumes:
        - name: artifact-staging
          hostPath:
            path: /run/desktop/mnt/host/c/flink/tmp
        - name: config
          configMap:
            name: config
      restartPolicy: Never

# kubectl create configmap config --from-file pipeline-submission.json -o yaml --dry-run=client | kubectl apply -f -